### PR TITLE
support deploy of hidden files

### PR DESCRIPTION
**Pull request by siddolo**
you can test with `ls -lah ./{.*/*,*/*,**}`

### CODE REVIEW

**Comment by Reggionick** [comment]
Hi @siddolo!
I thinks that this should be linked to a input param. For example `ignore-hidden` that's `true` for default

What do you think?

**Comment by nmarch213** [comment]
@Reggionick Would it be possible to get this feature pushed along? It seems like im having an issue deploying a folder `.well-known` as it seems to not pick-up hidden folders.

Is this the same thing or is there a work around for this?

image

**Comment by Reggionick** [comment]
@nmarch213 yes I think is the same, but you can test it with the command `ls -lah ./{.*/*,*/*,**}`.

I've not merged it et because I think it would be better to set this under an option that could be enabled or not by the user

**Comment by Reggionick** [comment]
A contribution would be appreciated 😉

**Comment by Reggionick** [comment]
Closed in favour of #85.

**Pull request closed without merging**
