### PR TITLE
Update node version and changed compiler

### PR DESCRIPTION
**Pull request by nabadeep25**
CHANGES
- Updated action to use node 20 (Because of [Github warning] (https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/))
- Changed compiler to [vercel/ncc](https://www.npmjs.com/package/@vercel/ncc) ( [zeit/ncc](https://www.npmjs.com/package/@zeit/ncc) is deprecated )

### CODE REVIEW

**Comment by ghandic** [comment]
eta on this?

**Review by Reggionick — APPROVED** [review]
LGTM

**Review by coliff — APPROVED** [review]

**Comment by jimji1005** [comment]
Looking forward to seeing this merged! 🙏🏻 thank you all for the contributions! 

@Reggionick @coliff @nabadeep25 💪🏻

**Comment by MikeMatusz** [comment]
@Reggionick Thanks for merging!  Are there plans to create a new release anytime soon?

**Pull request merged**
